In [1]:
print("hello world")

hello world


In [2]:
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [3]:
# get the keys of the documents and store it in the list
key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [4]:
# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [5]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = {term for document in documents for term in document.split()}
unique_terms

{'Analysis',
 'Article:',
 'Basics',
 'Case',
 'Data',
 'Pandas',
 'Sales',
 'Study:',
 'Tutorial:',
 'Visualization'}

In [6]:
# create a matrix for the document by using the unique term
document_term_matrix = {}

for term in unique_terms:
    document_term_matrix[term] = []
    
    for document in documents:
        if term in document:
            document_term_matrix[term].append(1)
        else: document_term_matrix[term].append(0)

document_term_matrix

{'Visualization': [0, 1, 0],
 'Analysis': [0, 0, 1],
 'Pandas': [1, 0, 0],
 'Article:': [1, 0, 0],
 'Tutorial:': [0, 1, 0],
 'Data': [0, 1, 0],
 'Study:': [0, 0, 1],
 'Sales': [0, 0, 1],
 'Basics': [1, 0, 0],
 'Case': [0, 0, 1]}

In [7]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

documents_array = np.array(document_content_list, dtype='object')

v1 = np.array(document_term_matrix['Case'])    
v2 = np.array(document_term_matrix['Study:'])

print(v1)
print(v2)
print('-------')
v3 = v1 & v2
print(v3)
# display the content document from the result
[document for document in v3 * documents_array if document]

[0 0 1]
[0 0 1]
-------
[0 0 1]


['Analyze sales data using Python for a real-world case study.']

In [8]:
# find the document for those have at least one word
v3 = v1 | v2
print(v3)
[document for document in v3 * documents_array if document]

[0 0 1]


['Analyze sales data using Python for a real-world case study.']

In [9]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
